%% Creaci�n de Diccionario 
% Solo se crea con las del testing.

load('all_data.mat');

offsets = [ 0.1,  0.1;...
            0.1,  0, ;...
            0.1, -0.1;...
            0  ,  0.1;...
            0  ,  0, ;...
            0  , -0.1;...
           -0.1,  0.1;...
           -0.1,  0, ;...
           -0.1, -0.1];

[D, person, photo, offset, patch] = parts_to_dict(all_data, offsets);

save('Dall.mat','D');
