source_folder = "./faces_lfwa_3_eq_local/";
indexes =[1,...
         16,...
         592,...
         765,...
        1194,...
        1470,...
        1836,...
        2009,...
        2016,...
        2069,...
        2468,...
        2486,... 
        2509,...
        2965,...
        3214,...
        3241,...
        3371,...
        4070];

load('all_data')
load('raw_faces_points_2')

for ii = indexes
  close all
  data = all_data{ii}.data;
  
  img = imread(all_data{ii}.filename);
  
  figure()
  subplot(2,3,[1,4]);
  imagesc(img)
  colormap('gray')
  axis('image')
  title(sprintf("Largo de datos: %d", size(detections{ii}{2}.xy, 1)))
  
  splo = [2,3,5,6];
  
  for jj = 1:length(data)
    img = data{jj};
    subplot(2,3,splo(jj));
    imagesc(img)
    colormap('gray')
    axis('image')
  end
  
  pause
  
end